# Generated by Django 6.0.2 on 2026-02-14 14:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_of_birth', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('registry_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patients',
                'indexes': [models.Index(fields=['email'], name='patients_email_bf0efb_idx'), models.Index(fields=['registry_id'], name='patients_registr_dabcdc_idx')],
            },
        ),
        migrations.CreateModel(
            name='VitalSign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('HR', 'Heart Rate'), ('BP', 'Blood Pressure'), ('Temp', 'Temperature'), ('SPO2', 'Oxygen Saturation')], max_length=30)),
                ('value', models.CharField(max_length=30)),
                ('measured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='healthcare.patient')),
            ],
            options={
                'db_table': 'vital_signs',
                'indexes': [models.Index(fields=['type'], name='vital_signs_type_e856d0_idx'), models.Index(fields=['measured_at'], name='vital_signs_measure_be0449_idx')],
            },
        ),
    ]
