# Generated by Django 6.0.2 on 2026-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitalsign',
            name='type',
            field=models.CharField(choices=[('HR', 'Heart Rate'), ('BP', 'Blood Pressure'), ('TEMP', 'Temperature'), ('SPO2', 'Oxygen Saturation')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vitalsign',
            name='value',
            field=models.CharField(max_length=20),
        ),
    ]
