# Generated by Django 6.0.2 on 2026-02-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0002_alter_vitalsign_type_alter_vitalsign_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='family_name',
            field=models.CharField(default='Unknown', max_length=60),
        ),
        migrations.AddField(
            model_name='patient',
            name='given_name',
            field=models.CharField(default='Unknown', max_length=60),
        ),
    ]
