# Generated by Django 6.0.2 on 2026-02-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcare', '0003_remove_patient_name_patient_family_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='family_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='given_name',
            field=models.CharField(max_length=60),
        ),
    ]
